# Generated by Django 2.2.6 on 2019-10-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Muscle Groups',
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.MuscleGroup')),
            ],
            options={
                'verbose_name_plural': 'Muscles',
            },
        ),
        migrations.CreateModel(
            name='ExerciseStress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workout.MuscleGroup')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workout.MuscleGroup')),
            ],
            options={
                'verbose_name': 'Exercise Stress',
                'verbose_name_plural': 'Exercise Stresses',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.MuscleGroup')),
                ('muscles', models.ManyToManyField(to='workout.Muscle')),
            ],
            options={
                'verbose_name_plural': 'Exercises',
            },
        ),
    ]
